# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every 12 hours)
  schedule:
    - cron: "0 */12 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub token with required scopes
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic configuration
          user: awesome-doge
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_display: large
          config_timezone: Asia/Taipei
          config_twemoji: yes

          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Lines plugin
          plugin_lines: yes
          plugin_lines_history_limit: 3
          plugin_lines_repositories_limit: 8
          plugin_lines_sections: base

          # Notable plugin
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          # People plugin
          plugin_people: yes
          plugin_people_limit: 25
          plugin_people_size: 30
          plugin_people_types: followers, following

          # Starlists plugin
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 1
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 5
          plugin_starlists_shuffle_repositories: yes

          # Stars plugin
          plugin_stars: yes
          plugin_stars_limit: 4

          # Topics plugin
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars

          # Traffic plugin
          plugin_traffic: yes

          # Repositories forks
          repositories_forks: yes

          # Additional features
          plugin_followup: yes
          plugin_followup_sections: base
